FROM appimagecrafters/appimage-builder:1.1.0

ENV XDG_DATA_DIRS "/usr/share:/usr/local/share"

RUN apt-get update && apt-get install -y --no-install-recommends adwaita-icon-theme && rm -rf /var/lib/apt/lists/* 
