site_name: nmfu
theme:
  name: readthedocs
  highlightjs: false

extra_css: ['css/extra.css']

nav:
  - Home: 'index.md'
  - Tutorials:
    - 'Simple HTTP': 'tutorial/http1.md'
    - 'Simple HTTP, continued': 'tutorial/http2.md'
  - 'User Reference':
    - 'Parser Specification': 'user-ref/parser.md'
    - 'Generated Code': 'user-ref/generated-code.md'
    - 'Command Line Options': 'user-ref/cli.md'


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      css_class: hcode
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
