name: nmfu
version: git
summary: A parser generator
description: A parser generator
grade: stable

confinement: strict
base: core20

parts:
    nmfu:
        plugin: python
        python-version: python3
        source: .

apps:
    nmfu:
        command: bin/nmfu
        plugs: [home, removable-media]
